"""
================================================================================
COORDINATED OUTAGE HANDLING MODULE
================================================================================

Implements coordinated outage modeling, shared generation scheduling,
demand reduction propagation, staged recovery, and outage metrics for
multi-microgrid digital twin systems.

Components:
    1. RegionalOutageGenerator  — Probabilistic outage event generation
    2. CascadeController        — Simplified cascading failure detection
    3. SharedGenScheduler       — Cross-MG generator coordination
    4. DemandReductionPropagator — Priority-weighted demand curtailment
    5. RecoveryController       — 4-phase staged reconnection
    6. StabilityMonitor         — Secondary instability prevention
    7. OutageMetricsCollector   — Per-run metric accumulation

Integration:
    - Hooks into CityEMS via _coordinate_outage_response()
    - Uses existing EnergyExchangeBus for power transfers
    - Extends EnhancedScenarioEngine for cascade injection
    - Feeds CoordinatedOutageScorecard to resilience calculator

Reference: Methodology Section — Coordinated Outage Handling
================================================================================
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple
from datetime import datetime, timedelta
from enum import Enum
import logging
import numpy as np
import uuid

logger = logging.getLogger(__name__)

# Import city EMS types
try:
    from src.ems.city_ems import MicrogridPriority, MicrogridStatus, SupervisoryCommand
except ImportError:
    from src.ems.city_ems import MicrogridPriority, MicrogridStatus, SupervisoryCommand


# =============================================================================
# OUTAGE SEVERITY AND EVENT MODELS
# =============================================================================

class OutageSeverity(Enum):
    """Severity levels for regional outage events."""
    MINOR = 1         # Single feeder, 1-2 MGs, <2h
    MODERATE = 2      # Distribution fault, 2-3 MGs, 2-6h
    MAJOR = 3         # Substation failure, all MGs, 6-24h
    CATASTROPHIC = 4  # Transmission failure, all MGs, 24-72h


@dataclass
class RegionalOutageEvent:
    """Extended outage event with severity, probability, and cascade support."""
    event_id: str
    start_time: datetime
    duration_hours: float
    affected_microgrids: List[str]
    severity: OutageSeverity
    description: str = ""

    # Probabilistic fields
    probability: float = 1.0            # Occurrence probability (for Monte Carlo)
    cascade_probability: float = 0.0    # Probability of triggering cascade
    propagation_delay_hours: float = 0.0  # Delay before cascading to neighbors
    weather_correlation: float = 0.0    # 0-1, correlation with weather events

    # Tracking
    is_cascade_event: bool = False      # True if generated by cascade logic
    parent_event_id: Optional[str] = None  # Source event that triggered cascade
    cascade_depth: int = 0              # Current cascade depth

    @property
    def end_time(self) -> datetime:
        return self.start_time + timedelta(hours=self.duration_hours)


# =============================================================================
# PROBABILISTIC OUTAGE GENERATOR
# =============================================================================

class RegionalOutageGenerator:
    """
    Monte Carlo outage generation using Poisson arrival + Weibull duration.

    Parameters are based on IEEE RBTS (Roy Billinton Test System)
    benchmarks adapted for tropical urban distribution networks.
    """

    # Outage rate parameters: lambda (events/day), shape k, scale (hours)
    RATE_PARAMS = {
        OutageSeverity.MINOR:        {'lambda': 0.15, 'k': 1.5, 'scale': 1.5},
        OutageSeverity.MODERATE:     {'lambda': 0.05, 'k': 2.0, 'scale': 4.0},
        OutageSeverity.MAJOR:        {'lambda': 0.01, 'k': 1.8, 'scale': 12.0},
        OutageSeverity.CATASTROPHIC: {'lambda': 0.002, 'k': 2.5, 'scale': 36.0},
    }

    # Geographic proximity: probability that MG_j is co-affected when MG_i fails
    PROXIMITY_MATRIX = {
        ('hospital', 'university'):   0.7,   # Same district
        ('hospital', 'industrial'):   0.3,   # Adjacent districts
        ('hospital', 'residential'):  0.4,
        ('university', 'industrial'): 0.5,
        ('university', 'residential'): 0.6,  # Same district
        ('industrial', 'residential'): 0.3,
    }

    # Cascade probability by severity
    CASCADE_PROB = {
        OutageSeverity.MINOR: 0.05,
        OutageSeverity.MODERATE: 0.15,
        OutageSeverity.MAJOR: 0.30,
        OutageSeverity.CATASTROPHIC: 0.50,
    }

    ALL_MICROGRIDS = ['hospital', 'university', 'industrial', 'residential']

    def __init__(self, seed: Optional[int] = None):
        self.rng = np.random.default_rng(seed)

    def generate_scenario(
        self,
        duration_days: float,
        start_time: datetime,
        severity_filter: Optional[List[OutageSeverity]] = None,
    ) -> List[RegionalOutageEvent]:
        """
        Generate stochastic outage timeline for simulation period.

        Args:
            duration_days: Simulation period in days.
            start_time: Simulation start time.
            severity_filter: Only generate events of these severities (None = all).

        Returns:
            List of RegionalOutageEvent sorted by start_time.
        """
        events = []
        severities = severity_filter or list(OutageSeverity)

        for severity in severities:
            params = self.RATE_PARAMS[severity]
            lam = params['lambda']

            # Generate event count via Poisson
            n_events = self.rng.poisson(lam * duration_days)

            for _ in range(n_events):
                # Random arrival time (uniform within period)
                offset_hours = self.rng.uniform(0, duration_days * 24)
                event_start = start_time + timedelta(hours=offset_hours)

                # Duration via Weibull
                duration = float(self.rng.weibull(params['k']) * params['scale'])
                duration = max(0.25, min(duration, 72.0))  # Clamp: 15min to 72h

                # Primary affected microgrid (random)
                primary_mg = self.rng.choice(self.ALL_MICROGRIDS)
                affected = [primary_mg]

                # Co-affected microgrids based on proximity
                if severity != OutageSeverity.MINOR:
                    for other_mg in self.ALL_MICROGRIDS:
                        if other_mg == primary_mg:
                            continue
                        key = tuple(sorted([primary_mg, other_mg]))
                        proximity = self.PROXIMITY_MATRIX.get(key, 0.1)

                        # Higher severity → higher co-failure probability
                        severity_boost = (severity.value - 1) * 0.15
                        if self.rng.random() < proximity + severity_boost:
                            affected.append(other_mg)

                # For MAJOR/CATASTROPHIC: always affect all MGs
                if severity in [OutageSeverity.MAJOR, OutageSeverity.CATASTROPHIC]:
                    affected = list(self.ALL_MICROGRIDS)

                event = RegionalOutageEvent(
                    event_id=f"outage_{uuid.uuid4().hex[:8]}",
                    start_time=event_start,
                    duration_hours=round(duration, 2),
                    affected_microgrids=affected,
                    severity=severity,
                    description=f"{severity.name} outage affecting {len(affected)} MGs",
                    cascade_probability=self.CASCADE_PROB[severity],
                )
                events.append(event)

        # Sort by start time
        events.sort(key=lambda e: e.start_time)
        logger.info(
            f"Generated {len(events)} outage events over {duration_days} days "
            f"(severities: {[s.name for s in severities]})"
        )
        return events


# =============================================================================
# CASCADING FAILURE CONTROLLER
# =============================================================================

@dataclass
class CascadeAnalysisRecord:
    """Per-decision record for cascade analysis and sensitivity studies."""
    timestamp: datetime
    mg_id: str
    utilization: float
    threshold: float
    cascade_triggered: bool
    cascade_depth: int
    parent_event_id: str
    additional_ens_kwh: float = 0.0  # ENS caused by this cascade


class CascadeController:
    """
    Simplified cascading failure model (no power flow physics).

    Cascade trigger: When a MG is islanded and its neighbors absorb extra
    load via the exchange bus, check if any neighbor exceeds capacity.
    If so, inject a delayed secondary fault event.

    Parameter justification:
    - OVERLOAD_THRESHOLD=1.10: IEEE Std 1547-2018 §8.2.1 specifies abnormal
      operating conditions trip at >110% rated voltage/current.
    - MAX_CASCADE_DEPTH=2: Standard N−1/N−2 contingency analysis; with a
      4-node network (diameter=2), deeper cascades are topologically impossible.
    - CASCADE_DELAY=0.25h: Matches 15-min simulation timestep (protection
      relay coordination timescale).
    """

    def __init__(
        self,
        overload_threshold: float = 1.10,
        max_cascade_depth: int = 2,
        cascade_duration_hours: float = 1.0,
        cascade_delay_hours: float = 0.25,
    ):
        self.overload_threshold = overload_threshold
        self.max_cascade_depth = max_cascade_depth
        self.cascade_duration_hours = cascade_duration_hours
        self.cascade_delay_hours = cascade_delay_hours

        self.cascade_events: List[RegionalOutageEvent] = []
        self.cascade_count = 0
        self.cascades_prevented = 0
        self.analysis_records: List[CascadeAnalysisRecord] = []

    def check_cascade(
        self,
        mg_statuses: Dict[str, MicrogridStatus],
        mg_infos: Dict,
        currently_faulted: set,
        current_time: datetime,
        parent_event_id: str = "manual",
        current_depth: int = 0,
    ) -> List[RegionalOutageEvent]:
        """
        Check if any non-faulted MG is overloaded → trigger secondary fault.
        """
        if current_depth >= self.max_cascade_depth:
            return []

        new_faults = []

        for mg_id, status in mg_statuses.items():
            if mg_id in currently_faulted:
                continue

            mg_info = mg_infos.get(mg_id)
            if not mg_info:
                continue

            if mg_info.total_capacity_kw <= 0:
                continue

            utilization = status.total_load_kw / mg_info.total_capacity_kw

            if utilization > self.overload_threshold:
                cascade_event = RegionalOutageEvent(
                    event_id=f"cascade_{uuid.uuid4().hex[:8]}",
                    start_time=current_time + timedelta(
                        hours=self.cascade_delay_hours
                    ),
                    duration_hours=self.cascade_duration_hours,
                    affected_microgrids=[mg_id],
                    severity=OutageSeverity.MINOR,
                    description=(
                        f"Cascade from {parent_event_id}: "
                        f"{mg_id} overloaded at {utilization:.0%}"
                    ),
                    is_cascade_event=True,
                    parent_event_id=parent_event_id,
                    cascade_depth=current_depth + 1,
                )
                new_faults.append(cascade_event)
                self.cascade_count += 1

                self.analysis_records.append(CascadeAnalysisRecord(
                    timestamp=current_time, mg_id=mg_id,
                    utilization=utilization,
                    threshold=self.overload_threshold,
                    cascade_triggered=True,
                    cascade_depth=current_depth + 1,
                    parent_event_id=parent_event_id,
                ))

                logger.warning(
                    f"CASCADE: {mg_id} overloaded at {utilization:.0%} → "
                    f"secondary fault in {self.cascade_delay_hours}h "
                    f"(depth={current_depth + 1})"
                )
            else:
                if utilization > 0.95:
                    self.cascades_prevented += 1
                    self.analysis_records.append(CascadeAnalysisRecord(
                        timestamp=current_time, mg_id=mg_id,
                        utilization=utilization,
                        threshold=self.overload_threshold,
                        cascade_triggered=False,
                        cascade_depth=current_depth,
                        parent_event_id=parent_event_id,
                    ))
                    logger.info(
                        f"CASCADE AVOIDED: {mg_id} at {utilization:.0%} "
                        f"(threshold {self.overload_threshold:.0%})"
                    )

        self.cascade_events.extend(new_faults)
        return new_faults

    def get_analysis_records(self) -> List[CascadeAnalysisRecord]:
        """Return all cascade analysis records for post-hoc study."""
        return list(self.analysis_records)


class CascadeSensitivityAnalyzer:
    """
    Sweep cascade parameters to evaluate robustness.

    Sweeps OVERLOAD_THRESHOLD from 1.00 to 1.30 (step 0.02) and
    MAX_CASCADE_DEPTH from 1 to 4. For each pair, collects:
    - cascade_count, total_cascade_duration_hours
    - additional_ens_kwh, cascade_prevention_rate
    """

    DEFAULT_THRESHOLDS = [round(1.00 + i * 0.02, 2) for i in range(16)]
    DEFAULT_DEPTHS = [1, 2, 3, 4]

    @staticmethod
    def sweep(
        thresholds: Optional[List[float]] = None,
        depths: Optional[List[int]] = None,
    ) -> List[dict]:
        """
        Generate parameter configurations for sensitivity analysis.

        Usage:
            configs = CascadeSensitivityAnalyzer.sweep()
            for cfg in configs:
                controller = CascadeController(**cfg)
                # ... run simulation ...
                results.append({**cfg, 'cascade_count': controller.cascade_count})

        Returns:
            List of dicts with constructor kwargs for CascadeController.
        """
        thresholds = thresholds or CascadeSensitivityAnalyzer.DEFAULT_THRESHOLDS
        depths = depths or CascadeSensitivityAnalyzer.DEFAULT_DEPTHS

        configs = []
        for thresh in thresholds:
            for depth in depths:
                configs.append({
                    'overload_threshold': thresh,
                    'max_cascade_depth': depth,
                })
        return configs

    @staticmethod
    def summarize_results(results: List[dict]) -> dict:
        """
        Aggregate sweep results for table/heatmap generation.

        Args:
            results: List of dicts with keys:
                overload_threshold, max_cascade_depth,
                cascade_count, cascades_prevented,
                total_ens_kwh

        Returns:
            Dict keyed by (threshold, depth) → aggregated metrics.
        """
        summary = {}
        for r in results:
            key = (r['overload_threshold'], r['max_cascade_depth'])
            if key not in summary:
                summary[key] = {
                    'runs': 0, 'total_cascades': 0,
                    'total_prevented': 0, 'total_ens': 0.0,
                }
            summary[key]['runs'] += 1
            summary[key]['total_cascades'] += r.get('cascade_count', 0)
            summary[key]['total_prevented'] += r.get('cascades_prevented', 0)
            summary[key]['total_ens'] += r.get('total_ens_kwh', 0.0)

        # Compute averages
        for key, v in summary.items():
            n = max(1, v['runs'])
            v['mean_cascades'] = v['total_cascades'] / n
            v['mean_prevented'] = v['total_prevented'] / n
            v['mean_ens'] = v['total_ens'] / n
            if v['total_cascades'] + v['total_prevented'] > 0:
                v['prevention_rate'] = (
                    v['total_prevented']
                    / (v['total_cascades'] + v['total_prevented'])
                )
            else:
                v['prevention_rate'] = 1.0

        return summary


# =============================================================================
# SHARED GENERATION SCHEDULER
# =============================================================================

@dataclass
class GenDispatchCommand:
    """Command for generator dispatch coordination."""
    microgrid_id: str
    generator_on: bool
    power_setpoint_kw: float
    fuel_share_for_mg: Optional[str] = None  # Destination MG if shared
    reason: str = ""


class SharedGenScheduler:
    """
    Cross-microgrid generator scheduling during outages.

    Priority rules:
    - Hospital generators NEVER shared (dedicated critical backup)
    - Other generators shared only if donor SOC > threshold
    - Dispatch to highest-priority deficit first
    - Respect minimum fuel reserve per MG priority
    """

    # Minimum fuel reserve (hours at rated power) by priority
    MIN_FUEL_RESERVE = {
        MicrogridPriority.CRITICAL: 8.0,
        MicrogridPriority.HIGH: 4.0,
        MicrogridPriority.MEDIUM: 2.0,
        MicrogridPriority.LOW: 1.0,
    }

    # Minimum SOC for generator sharing eligibility
    MIN_SHARE_SOC = {
        MicrogridPriority.CRITICAL: 999.0,  # Hospital: never share
        MicrogridPriority.HIGH: 60.0,
        MicrogridPriority.MEDIUM: 40.0,
        MicrogridPriority.LOW: 50.0,
    }

    def __init__(self):
        self.dispatch_history: List[GenDispatchCommand] = []
        self.total_shared_kwh = 0.0
        self.per_step_records: List[dict] = []  # Per-step donor/recipient tracking

    def schedule(
        self,
        mg_statuses: Dict[str, MicrogridStatus],
        mg_infos: Dict,
        dt_hours: float = 0.25,
    ) -> Dict[str, GenDispatchCommand]:
        """
        Compute generator dispatch commands across all microgrids.

        Algorithm:
        1. Identify MGs with surplus generator capacity
        2. Identify MGs with deficit (load > generation + battery)
        3. Sort donors by efficiency, recipients by priority
        4. Allocate surplus gen to deficits, respecting fuel reserves

        Returns:
            Dict of GenDispatchCommand per microgrid.
        """
        commands = {}

        # Identify surplus (donors) and deficit (recipients)
        donors = []
        recipients = []

        for mg_id, status in mg_statuses.items():
            mg_info = mg_infos.get(mg_id)
            if not mg_info:
                continue

            net_balance = (
                status.pv_generation_kw
                + status.generator_power_kw
                + max(0, status.battery_power_kw)  # Discharge only
                - status.total_load_kw
            )

            # Check if this MG can share gen
            share_soc = self.MIN_SHARE_SOC.get(mg_info.priority, 999.0)

            if (net_balance > 10.0
                    and status.battery_soc_percent > share_soc
                    and mg_info.priority != MicrogridPriority.CRITICAL):
                # Has surplus and eligible to share
                # Check fuel reserve
                fuel_reserve_hours = self._fuel_hours_remaining(
                    status, mg_info
                )
                min_reserve = self.MIN_FUEL_RESERVE.get(
                    mg_info.priority, 2.0
                )

                if fuel_reserve_hours > min_reserve:
                    donors.append({
                        'mg_id': mg_id,
                        'available_kw': net_balance * 0.5,  # Share half
                        'fuel_hours': fuel_reserve_hours,
                        'priority': mg_info.priority,
                    })

            elif net_balance < -5.0 or status.load_shed_kw > 5.0:
                # Has deficit or is shedding
                deficit = max(abs(net_balance), status.load_shed_kw)
                recipients.append({
                    'mg_id': mg_id,
                    'deficit_kw': deficit,
                    'priority': mg_info.priority,
                    'critical_at_risk': status.critical_load_shed,
                })

        # Sort: donors by available power (largest first)
        donors.sort(key=lambda d: -d['available_kw'])

        # Sort: recipients by priority (CRITICAL first), then deficit
        recipients.sort(key=lambda r: (
            0 if r['critical_at_risk'] else 1,
            r['priority'].value,
            -r['deficit_kw'],
        ))

        # Allocate
        remaining_donor = {d['mg_id']: d['available_kw'] for d in donors}

        for recipient in recipients:
            rec_id = recipient['mg_id']
            remaining_need = recipient['deficit_kw']

            for donor in donors:
                don_id = donor['mg_id']
                available = remaining_donor.get(don_id, 0)

                if available < 5.0 or remaining_need < 5.0:
                    continue

                allocated = min(available, remaining_need)
                remaining_donor[don_id] -= allocated
                remaining_need -= allocated

                cmd = GenDispatchCommand(
                    microgrid_id=don_id,
                    generator_on=True,
                    power_setpoint_kw=allocated,
                    fuel_share_for_mg=rec_id,
                    reason=f"Shared gen: {don_id}→{rec_id} ({allocated:.0f}kW)"
                )
                commands[f"{don_id}_for_{rec_id}"] = cmd
                self.total_shared_kwh += allocated * dt_hours
                self.dispatch_history.append(cmd)

                self.per_step_records.append({
                    'donor': don_id,
                    'recipient': rec_id,
                    'kw': allocated,
                    'donor_fuel_remaining': (
                        mg_statuses[don_id].fuel_remaining_liters
                        if don_id in mg_statuses else 0
                    ),
                    'donor_soc': (
                        mg_statuses[don_id].battery_soc_percent
                        if don_id in mg_statuses else 0
                    ),
                })

                logger.info(cmd.reason)

                if remaining_need < 5.0:
                    break

        return commands

    @staticmethod
    def _fuel_hours_remaining(status: MicrogridStatus, mg_info) -> float:
        """Estimate fuel-hours remaining at current generator output."""
        if status.generator_power_kw <= 0:
            return 999.0
        # Rough: 0.25 L/kWh fuel consumption
        fuel_kwh = status.fuel_remaining_liters / 0.25
        return fuel_kwh / max(1.0, status.generator_power_kw)


# =============================================================================
# DEMAND REDUCTION PROPAGATION
# =============================================================================

class DemandReductionPropagator:
    """
    Propagates load shedding decisions across microgrids based on
    city-wide power balance and priority weights.
    """

    SHED_LIMITS = {
        MicrogridPriority.CRITICAL: 0.0,   # Hospital: never shed
        MicrogridPriority.HIGH: 30.0,      # University: up to 30%
        MicrogridPriority.MEDIUM: 70.0,    # Industrial: up to 70%
        MicrogridPriority.LOW: 90.0,       # Residential: up to 90%
    }

    # Restoration order (highest priority restored first)
    RESTORATION_ORDER = [
        MicrogridPriority.CRITICAL,
        MicrogridPriority.HIGH,
        MicrogridPriority.MEDIUM,
        MicrogridPriority.LOW,
    ]

    SHED_STEP_PERCENT = 10.0  # Staged reduction: 10% increments

    def __init__(self):
        self.current_shed: Dict[str, float] = {}  # mg_id → shed_percent
        self.total_reduction_kwh = 0.0
        self.shed_history: List[Dict[str, float]] = []  # Per-step shed snapshots

    def propagate(
        self,
        mg_statuses: Dict[str, MicrogridStatus],
        mg_infos: Dict,
        city_deficit_kw: float,
        dt_hours: float = 0.25,
    ) -> Dict[str, float]:
        """
        Compute priority-weighted load shedding allocation.

        Args:
            mg_statuses: Current MG statuses.
            mg_infos: MG info registry.
            city_deficit_kw: Total city-wide power deficit (positive = deficit).
            dt_hours: Timestep duration.

        Returns:
            Dict of mg_id → target shed percent.
        """
        if city_deficit_kw <= 0:
            # No deficit → gradually restore
            return self._restore_loads(mg_infos)

        # Calculate shedding allocation: lowest priority sheds first
        allocation = {}
        remaining_deficit = city_deficit_kw

        # Process in reverse priority (LOW → CRITICAL)
        priority_groups = self._group_by_priority(mg_statuses, mg_infos)

        for priority in reversed(self.RESTORATION_ORDER):
            if remaining_deficit <= 0:
                break

            group = priority_groups.get(priority, [])
            max_shed = self.SHED_LIMITS.get(priority, 0.0)

            for mg_id, status in group:
                if remaining_deficit <= 0:
                    break

                current = self.current_shed.get(mg_id, 0.0)
                # Increase shed by one step, capped at limit
                new_shed = min(current + self.SHED_STEP_PERCENT, max_shed)

                shed_power = status.total_load_kw * (new_shed / 100.0)
                current_power = status.total_load_kw * (current / 100.0)
                gained = shed_power - current_power

                allocation[mg_id] = new_shed
                self.current_shed[mg_id] = new_shed
                remaining_deficit -= gained

                if gained > 0:
                    self.total_reduction_kwh += gained * dt_hours

        # MGs not needing shed keep their current level
        for mg_id in mg_statuses:
            if mg_id not in allocation:
                allocation[mg_id] = self.current_shed.get(mg_id, 0.0)

        self.shed_history.append(dict(allocation))
        return allocation

    def get_priority_violation_count(self, mg_infos: Dict) -> int:
        """Count steps where higher-priority MG sheds while lower-priority has capacity."""
        violations = 0
        for snapshot in self.shed_history:
            priority_shedding = {}
            for mg_id, shed_pct in snapshot.items():
                info = mg_infos.get(mg_id)
                if info:
                    priority_shedding[info.priority] = max(
                        priority_shedding.get(info.priority, 0.0), shed_pct
                    )
            # Check: higher priority shedding while lower priority has room
            for p_high in [MicrogridPriority.CRITICAL, MicrogridPriority.HIGH]:
                for p_low in [MicrogridPriority.MEDIUM, MicrogridPriority.LOW]:
                    if (priority_shedding.get(p_high, 0) > 0
                            and priority_shedding.get(p_low, 0) < 50):
                        violations += 1
                        break
        return violations

    def _restore_loads(self, mg_infos: Dict) -> Dict[str, float]:
        """Gradually restore loads in priority order."""
        allocation = {}
        for priority in self.RESTORATION_ORDER:
            for mg_id, info in mg_infos.items():
                if info.priority == priority:
                    current = self.current_shed.get(mg_id, 0.0)
                    new_shed = max(0.0, current - self.SHED_STEP_PERCENT)
                    allocation[mg_id] = new_shed
                    self.current_shed[mg_id] = new_shed
        return allocation

    @staticmethod
    def _group_by_priority(
        statuses: Dict[str, MicrogridStatus],
        infos: Dict,
    ) -> Dict[MicrogridPriority, List[Tuple[str, MicrogridStatus]]]:
        """Group microgrids by priority level."""
        groups: Dict[MicrogridPriority, List] = {}
        for mg_id, status in statuses.items():
            info = infos.get(mg_id)
            if not info:
                continue
            groups.setdefault(info.priority, []).append((mg_id, status))
        return groups


# =============================================================================
# RECOVERY CONTROLLER
# =============================================================================

class RecoveryPhase(Enum):
    """Staged recovery phases."""
    INACTIVE = 0
    PREPARATION = 1
    CRITICAL_RECONNECT = 2
    STAGED_RESTORATION = 3
    STABILIZATION = 4
    COMPLETE = 5


@dataclass
class RecoveryPhaseRecord:
    """Per-phase timing, SOC trajectory, and fuel consumption record."""
    phase: RecoveryPhase
    entry_time: Optional[datetime] = None
    exit_time: Optional[datetime] = None
    duration_steps: int = 0
    avg_battery_soc: Dict[str, float] = field(default_factory=dict)
    gen_fuel_consumed_liters: Dict[str, float] = field(default_factory=dict)
    stability_checks_passed: int = 0
    stability_checks_failed: int = 0
    load_ramp_factor: float = 0.0


@dataclass
class StabilityEvent:
    """Individual stability check event for temporal analysis."""
    timestamp: Optional[datetime]
    mg_id: str
    check_type: str   # 'load_pickup', 'soc_drop', 'fuel_critical', 'city_load'
    value: float
    threshold: float
    passed: bool


class RecoveryController:
    """
    4-phase staged reconnection controller.

    Phase sequence:
    1. PREPARATION: Verify grid stability, pre-charge batteries
    2. CRITICAL_RECONNECT: Reconnect hospital, wait for stability
    3. STAGED_RESTORATION: Reconnect remaining MGs in priority order
    4. STABILIZATION: Generator ramp-down, battery recovery, monitoring
    """

    RECONNECTION_SEQUENCE = [
        'hospital', 'university', 'industrial', 'residential'
    ]

    LOAD_RAMP_SCHEDULE = [0.25, 0.50, 0.75, 1.00]
    GEN_RAMPDOWN_RATE = 0.10      # 10% per step
    STABILITY_CHECK_STEPS = 2     # Wait 2 steps (30 min) between reconnections
    STABILIZATION_STEPS = 4       # Monitor for 1 hour
    MIN_BATTERY_FOR_RECONNECT = 60.0  # % SOC before reconnecting

    def __init__(self):
        self.phase = RecoveryPhase.INACTIVE
        self.phase_entry_step = 0
        self.steps_in_phase = 0
        self.reconnected_mgs: List[str] = []
        self.next_reconnect_idx = 0
        self.load_ramp_step = 0
        self.gen_ramp_factor: Dict[str, float] = {}
        # Phase records for per-phase analysis
        self.phase_records: List[RecoveryPhaseRecord] = []
        self._current_record: Optional[RecoveryPhaseRecord] = None
        self._phase_soc_samples: Dict[str, List[float]] = {}
        self._phase_fuel_start: Dict[str, float] = {}

    def start_recovery(self, current_step: int):
        """Initiate recovery sequence when grid restoration is detected."""
        if self.phase == RecoveryPhase.INACTIVE:
            self.phase = RecoveryPhase.PREPARATION
            self.phase_entry_step = current_step
            self.steps_in_phase = 0
            self._start_phase_record(RecoveryPhase.PREPARATION)
            logger.info("RECOVERY: Entering PREPARATION phase")

    def _start_phase_record(self, phase: RecoveryPhase, ts: Optional[datetime] = None):
        """Begin tracking a new recovery phase."""
        if self._current_record is not None:
            self._finalize_phase_record()
        self._current_record = RecoveryPhaseRecord(
            phase=phase, entry_time=ts, duration_steps=0
        )
        self._phase_soc_samples = {}
        self._phase_fuel_start = {}

    def _finalize_phase_record(self, ts: Optional[datetime] = None):
        """Close current phase record and store it."""
        if self._current_record is None:
            return
        self._current_record.exit_time = ts
        self._current_record.duration_steps = self.steps_in_phase
        # Compute average SOC per MG during this phase
        for mg_id, samples in self._phase_soc_samples.items():
            if samples:
                self._current_record.avg_battery_soc[mg_id] = (
                    sum(samples) / len(samples)
                )
        self.phase_records.append(self._current_record)
        self._current_record = None

    def _record_step_snapshot(self, statuses: Dict[str, MicrogridStatus]):
        """Record per-step SOC and fuel for current phase."""
        for mg_id, status in statuses.items():
            self._phase_soc_samples.setdefault(mg_id, []).append(
                status.battery_soc_percent
            )
            if mg_id not in self._phase_fuel_start:
                self._phase_fuel_start[mg_id] = status.fuel_remaining_liters

    def update(
        self,
        mg_statuses: Dict[str, MicrogridStatus],
        mg_infos: Dict,
        current_step: int,
        grid_available: Dict[str, bool],
    ) -> Dict[str, SupervisoryCommand]:
        """
        Execute one recovery step. Returns supervisory commands.

        Args:
            mg_statuses: Current MG statuses.
            mg_infos: MG info registry.
            current_step: Current simulation step.
            grid_available: Dict of mg_id → grid availability.

        Returns:
            Dict of SupervisoryCommand per microgrid.
        """
        commands = {}
        self.steps_in_phase += 1
        timestamp = datetime.now()
        if mg_statuses:
            first_status = next(iter(mg_statuses.values()))
            timestamp = first_status.timestamp

        # Record step snapshot for current phase
        self._record_step_snapshot(mg_statuses)

        if self.phase == RecoveryPhase.PREPARATION:
            commands = self._phase_preparation(mg_statuses, mg_infos, timestamp)

        elif self.phase == RecoveryPhase.CRITICAL_RECONNECT:
            commands = self._phase_critical_reconnect(
                mg_statuses, mg_infos, timestamp
            )

        elif self.phase == RecoveryPhase.STAGED_RESTORATION:
            commands = self._phase_staged_restoration(
                mg_statuses, mg_infos, timestamp
            )

        elif self.phase == RecoveryPhase.STABILIZATION:
            commands = self._phase_stabilization(
                mg_statuses, mg_infos, timestamp
            )

        return commands

    def _phase_preparation(self, statuses, infos, ts) -> Dict:
        """Phase 1: Verify stability, pre-charge batteries."""
        commands = {}

        all_ready = True
        for mg_id, status in statuses.items():
            cmd = SupervisoryCommand(
                microgrid_id=mg_id, timestamp=ts,
                battery_soc_target_percent=80.0,
                reason="Recovery PREPARATION: pre-charging battery"
            )

            # Check readiness
            if status.battery_soc_percent < self.MIN_BATTERY_FOR_RECONNECT:
                cmd.generator_enable = True  # Use gen to charge
                all_ready = False

            # Reduce gen by 25% in preparation
            self.gen_ramp_factor[mg_id] = 0.75
            commands[mg_id] = cmd

        # Advance to next phase after 2 steps or when ready
        if all_ready or self.steps_in_phase >= self.STABILITY_CHECK_STEPS:
            self._start_phase_record(RecoveryPhase.CRITICAL_RECONNECT, ts)
            self.phase = RecoveryPhase.CRITICAL_RECONNECT
            self.steps_in_phase = 0
            logger.info("RECOVERY: Advancing to CRITICAL_RECONNECT")

        return commands

    def _phase_critical_reconnect(self, statuses, infos, ts) -> Dict:
        """Phase 2: Reconnect hospital first, wait for stability."""
        commands = {}
        hospital_id = self.RECONNECTION_SEQUENCE[0]

        for mg_id, status in statuses.items():
            cmd = SupervisoryCommand(microgrid_id=mg_id, timestamp=ts)

            if mg_id == hospital_id:
                cmd.target_shed_percent = 0.0
                cmd.battery_soc_target_percent = 85.0
                cmd.reason = "Recovery: Hospital reconnected (P1)"
                if mg_id not in self.reconnected_mgs:
                    self.reconnected_mgs.append(mg_id)
            else:
                cmd.battery_soc_target_percent = 80.0
                cmd.reason = "Recovery: Awaiting reconnection"

            commands[mg_id] = cmd

        # Wait for stability then advance
        if self.steps_in_phase >= self.STABILITY_CHECK_STEPS:
            self._start_phase_record(RecoveryPhase.STAGED_RESTORATION, ts)
            self.phase = RecoveryPhase.STAGED_RESTORATION
            self.steps_in_phase = 0
            self.next_reconnect_idx = 1
            self.load_ramp_step = 0
            logger.info("RECOVERY: Advancing to STAGED_RESTORATION")

        return commands

    def _phase_staged_restoration(self, statuses, infos, ts) -> Dict:
        """Phase 3: Reconnect remaining MGs in priority order."""
        commands = {}

        # Determine which MG to reconnect this step
        reconnect_mg = None
        if (self.next_reconnect_idx < len(self.RECONNECTION_SEQUENCE)
                and self.steps_in_phase % (self.STABILITY_CHECK_STEPS + 1) == 0):
            reconnect_mg = self.RECONNECTION_SEQUENCE[self.next_reconnect_idx]
            if reconnect_mg not in self.reconnected_mgs:
                self.reconnected_mgs.append(reconnect_mg)
                logger.info(f"RECOVERY: Reconnecting {reconnect_mg}")
            self.next_reconnect_idx += 1

        # Compute load ramp for reconnected MGs
        ramp_idx = min(self.load_ramp_step, len(self.LOAD_RAMP_SCHEDULE) - 1)
        ramp_factor = self.LOAD_RAMP_SCHEDULE[ramp_idx]

        for mg_id, status in statuses.items():
            cmd = SupervisoryCommand(microgrid_id=mg_id, timestamp=ts)

            if mg_id in self.reconnected_mgs:
                # Gradual load pickup
                shed_pct = (1.0 - ramp_factor) * 100.0
                cmd.target_shed_percent = max(0.0, shed_pct)
                cmd.battery_soc_target_percent = 85.0
                cmd.reason = (
                    f"Recovery: {mg_id} at {ramp_factor:.0%} load "
                    f"(ramp step {ramp_idx + 1})"
                )
            else:
                cmd.battery_soc_target_percent = 80.0
                cmd.reason = "Recovery: Awaiting reconnection"

            commands[mg_id] = cmd

        self.load_ramp_step += 1

        # Advance when all MGs are reconnected and at full load
        if (self.next_reconnect_idx >= len(self.RECONNECTION_SEQUENCE)
                and ramp_factor >= 1.0):
            self._start_phase_record(RecoveryPhase.STABILIZATION, ts)
            self.phase = RecoveryPhase.STABILIZATION
            self.steps_in_phase = 0
            logger.info("RECOVERY: Advancing to STABILIZATION")

        return commands

    def _phase_stabilization(self, statuses, infos, ts) -> Dict:
        """Phase 4: Generator ramp-down, battery recovery, monitoring."""
        commands = {}

        for mg_id, status in statuses.items():
            cmd = SupervisoryCommand(microgrid_id=mg_id, timestamp=ts)

            # Generator ramp-down
            current_factor = self.gen_ramp_factor.get(mg_id, 1.0)
            new_factor = max(0.0, current_factor - self.GEN_RAMPDOWN_RATE)
            self.gen_ramp_factor[mg_id] = new_factor

            if new_factor <= 0.0:
                cmd.generator_enable = False
                cmd.reason = "Recovery: Generator off, stabilized"
            else:
                cmd.generator_enable = True
                cmd.reason = (
                    f"Recovery: Gen ramp-down {new_factor:.0%} "
                    f"(step {self.steps_in_phase})"
                )

            # Battery: float charge to 90%
            cmd.battery_soc_target_percent = 90.0
            cmd.target_shed_percent = 0.0

            commands[mg_id] = cmd

        # Complete after monitoring period
        if self.steps_in_phase >= self.STABILIZATION_STEPS:
            self._finalize_phase_record(ts)
            self.phase = RecoveryPhase.COMPLETE
            logger.info("RECOVERY: COMPLETE — all systems normal")

        return commands

    @property
    def is_active(self) -> bool:
        return self.phase not in [RecoveryPhase.INACTIVE, RecoveryPhase.COMPLETE]

    @property
    def is_complete(self) -> bool:
        return self.phase == RecoveryPhase.COMPLETE


# =============================================================================
# STABILITY MONITOR
# =============================================================================

class StabilityMonitor:
    """
    Monitors for secondary instability during recovery.

    Checks:
    1. Load pickup rate: >20% capacity increase in one step → pause
    2. Battery SOC drop: >5% drop during recovery → slow down
    3. Generator fuel: <2h reserve → hold generators
    4. Aggregate load: >90% city capacity → staged approach
    """

    LOAD_PICKUP_LIMIT = 0.20
    SOC_DROP_LIMIT = 5.0
    FUEL_CRITICAL_HOURS = 2.0
    CITY_LOAD_LIMIT = 0.90

    def __init__(self):
        self.previous_loads: Dict[str, float] = {}
        self.previous_socs: Dict[str, float] = {}
        self.instability_events = 0
        self.events: List[StabilityEvent] = []

    def check_stability(
        self,
        mg_statuses: Dict[str, MicrogridStatus],
        mg_infos: Dict,
    ) -> Tuple[bool, str]:
        """Check system stability. Returns (is_stable, reason)."""
        ts = None
        if mg_statuses:
            first = next(iter(mg_statuses.values()))
            ts = getattr(first, 'timestamp', None)

        for mg_id, status in mg_statuses.items():
            mg_info = mg_infos.get(mg_id)
            if not mg_info:
                continue

            # Check 1: Load pickup rate
            prev_load = self.previous_loads.get(mg_id, status.total_load_kw)
            load_increase = (
                (status.total_load_kw - prev_load) / mg_info.total_capacity_kw
            )
            self.events.append(StabilityEvent(
                timestamp=ts, mg_id=mg_id, check_type='load_pickup',
                value=load_increase, threshold=self.LOAD_PICKUP_LIMIT,
                passed=load_increase <= self.LOAD_PICKUP_LIMIT,
            ))
            if load_increase > self.LOAD_PICKUP_LIMIT:
                self.instability_events += 1
                self._update_previous(mg_statuses)
                return False, (
                    f"{mg_id}: load pickup {load_increase:.0%} "
                    f"> {self.LOAD_PICKUP_LIMIT:.0%} limit"
                )

            # Check 2: Battery SOC drop
            prev_soc = self.previous_socs.get(
                mg_id, status.battery_soc_percent
            )
            soc_drop = prev_soc - status.battery_soc_percent
            self.events.append(StabilityEvent(
                timestamp=ts, mg_id=mg_id, check_type='soc_drop',
                value=soc_drop, threshold=self.SOC_DROP_LIMIT,
                passed=soc_drop <= self.SOC_DROP_LIMIT,
            ))
            if soc_drop > self.SOC_DROP_LIMIT:
                self.instability_events += 1
                self._update_previous(mg_statuses)
                return False, (
                    f"{mg_id}: SOC drop {soc_drop:.1f}% > {self.SOC_DROP_LIMIT}%"
                )

            # Check 3: Fuel critical
            if status.fuel_remaining_liters > 0:
                fuel_hours = status.fuel_remaining_liters / max(
                    1.0, status.generator_power_kw * 0.25
                )
                self.events.append(StabilityEvent(
                    timestamp=ts, mg_id=mg_id, check_type='fuel_critical',
                    value=fuel_hours, threshold=self.FUEL_CRITICAL_HOURS,
                    passed=fuel_hours >= self.FUEL_CRITICAL_HOURS,
                ))
                if fuel_hours < self.FUEL_CRITICAL_HOURS:
                    self.instability_events += 1
                    self._update_previous(mg_statuses)
                    return False, f"{mg_id}: fuel < {self.FUEL_CRITICAL_HOURS}h"

        # Check 4: City-wide utilization
        total_load = sum(s.total_load_kw for s in mg_statuses.values())
        total_capacity = sum(
            mg_infos[mg_id].total_capacity_kw
            for mg_id in mg_statuses
            if mg_id in mg_infos
        )
        if total_capacity > 0:
            city_util = total_load / total_capacity
            self.events.append(StabilityEvent(
                timestamp=ts, mg_id='city',
                check_type='city_load',
                value=city_util, threshold=self.CITY_LOAD_LIMIT,
                passed=city_util <= self.CITY_LOAD_LIMIT,
            ))
            if city_util > self.CITY_LOAD_LIMIT:
                self.instability_events += 1
                self._update_previous(mg_statuses)
                return False, (
                    f"City load {city_util:.0%} > {self.CITY_LOAD_LIMIT:.0%}"
                )

        self._update_previous(mg_statuses)
        return True, "Stable"

    def get_event_distribution(self) -> Dict[str, int]:
        """Return count of events by check_type (failed checks only)."""
        dist: Dict[str, int] = {}
        for e in self.events:
            if not e.passed:
                dist[e.check_type] = dist.get(e.check_type, 0) + 1
        return dist

    def _update_previous(self, statuses: Dict[str, MicrogridStatus]):
        for mg_id, status in statuses.items():
            self.previous_loads[mg_id] = status.total_load_kw
            self.previous_socs[mg_id] = status.battery_soc_percent


# =============================================================================
# OUTAGE METRICS COLLECTOR
# =============================================================================

@dataclass
class StandardReliabilityIndices:
    """Maps simulation metrics to IEEE Std 1366-2012 reliability indices.

    Reference: IEEE Std 1366-2012, "IEEE Guide for Electric Power
    Distribution Reliability Indices."
    """
    SAIDI: float = 0.0   # System Avg Interruption Duration Index (hours)
    SAIFI: float = 0.0   # System Avg Interruption Frequency Index
    CAIDI: float = 0.0   # Customer Avg Interruption Duration (hours)
    EENS: float = 0.0    # Expected Energy Not Served (kWh)
    LOLP: float = 0.0    # Loss of Load Probability (fraction)
    ASAI: float = 0.0    # Average Service Availability Index


@dataclass
class CoordinatedOutageScorecard:
    """Extended scorecard with coordination-specific metrics."""

    # Core resilience (from existing)
    city_survivability_index: float = 1.0
    total_unserved_energy_kwh: float = 0.0
    critical_unserved_energy_kwh: float = 0.0
    recovery_time_hours: float = 0.0

    # Coordination-specific
    cascade_events_triggered: int = 0
    cascade_events_prevented: int = 0
    shared_generation_kwh: float = 0.0
    demand_reduction_kwh: float = 0.0
    energy_exchanged_kwh: float = 0.0
    recovery_phases_completed: int = 0
    secondary_instability_events: int = 0
    mean_recovery_time_hours: float = 0.0
    generator_usage_total_kwh: float = 0.0
    generator_usage_reduction_percent: float = 0.0

    # IEEE 1366-2012 standard indices
    standard_indices: Optional[StandardReliabilityIndices] = None

    # Per-outage breakdown
    outage_metrics: List[dict] = field(default_factory=list)


class OutageMetricsCollector:
    """
    Accumulates per-timestep metrics during simulation.
    Produces a CoordinatedOutageScorecard at simulation end.

    Granular tracking includes per-MG ENS, SOC, gen power, and
    shed percentage at each timestep for DataFrame export.
    """

    N_MICROGRIDS = 4  # Used for SAIDI/SAIFI computation

    def __init__(self):
        self.total_ens_kwh = 0.0
        self.critical_ens_kwh = 0.0
        self.gen_energy_kwh = 0.0
        self.shared_energy_kwh = 0.0
        self.exchanged_energy_kwh = 0.0
        self.demand_reduction_kwh = 0.0
        self.outage_start: Optional[datetime] = None
        self.outage_end: Optional[datetime] = None
        self.recovery_start: Optional[datetime] = None
        self.recovery_end: Optional[datetime] = None
        self.timestep_data: List[dict] = []
        # Per-MG ENS tracking
        self.per_mg_ens: Dict[str, float] = {}
        # Interruption tracking for standard indices
        self._interruption_events: int = 0
        self._interruption_mg_hours: float = 0.0  # Sum(interrupted_MGs × dt)
        self._steps_with_shedding: int = 0
        self._total_steps: int = 0

    def update(
        self,
        mg_statuses: Dict[str, MicrogridStatus],
        resource_transfers: List,
        recovery_phase: RecoveryPhase,
        gen_shared_kwh: float = 0.0,
        demand_reduced_kwh: float = 0.0,
        dt_hours: float = 0.25,
    ):
        """Per-timestep metric update with granular per-MG tracking."""
        self._total_steps += 1
        per_mg_shed = {}
        per_mg_gen = {}
        per_mg_soc = {}
        interrupted_count = 0

        for mg_id, status in mg_statuses.items():
            shed_kwh = status.load_shed_kw * dt_hours
            self.total_ens_kwh += shed_kwh
            self.per_mg_ens[mg_id] = self.per_mg_ens.get(mg_id, 0) + shed_kwh
            if status.critical_load_shed:
                self.critical_ens_kwh += shed_kwh

            self.gen_energy_kwh += status.generator_power_kw * dt_hours

            per_mg_shed[mg_id] = status.load_shed_kw
            per_mg_gen[mg_id] = status.generator_power_kw
            per_mg_soc[mg_id] = status.battery_soc_percent

            if status.is_islanded or status.load_shed_kw > 0:
                interrupted_count += 1

        # Track interruptions for SAIDI/SAIFI
        if interrupted_count > 0:
            self._steps_with_shedding += 1
            self._interruption_mg_hours += interrupted_count * dt_hours
            self._interruption_events += 1

        # Resource sharing transfers
        if resource_transfers:
            for t in resource_transfers:
                self.exchanged_energy_kwh += t.delivered_kw * dt_hours

        self.shared_energy_kwh += gen_shared_kwh
        self.demand_reduction_kwh += demand_reduced_kwh

        # Track outage timing
        any_islanded = any(s.is_islanded for s in mg_statuses.values())
        ts = next(iter(mg_statuses.values())).timestamp if mg_statuses else None

        if any_islanded and self.outage_start is None:
            self.outage_start = ts
        if not any_islanded and self.outage_start and self.outage_end is None:
            self.outage_end = ts

        if recovery_phase != RecoveryPhase.INACTIVE:
            if self.recovery_start is None:
                self.recovery_start = ts
            if recovery_phase == RecoveryPhase.COMPLETE:
                self.recovery_end = ts

        # City deficit
        total_load = sum(s.total_load_kw for s in mg_statuses.values())
        total_gen = sum(
            s.pv_generation_kw + s.generator_power_kw
            for s in mg_statuses.values()
        )

        # Store granular timestep snapshot
        self.timestep_data.append({
            'timestamp': ts,
            'total_ens_kwh': self.total_ens_kwh,
            'gen_energy_kwh': self.gen_energy_kwh,
            'exchanged_kwh': self.exchanged_energy_kwh,
            'recovery_phase': recovery_phase.name,
            'per_mg_shed': dict(per_mg_shed),
            'per_mg_gen_kw': dict(per_mg_gen),
            'per_mg_soc': dict(per_mg_soc),
            'city_deficit_kw': max(0, total_load - total_gen),
        })

    def compute_standard_indices(self) -> StandardReliabilityIndices:
        """
        Compute IEEE Std 1366-2012 reliability indices from simulation data.

        Formulae:
        - SAIDI = Σ(r_i × N_i) / N_T  [hours]
        - SAIFI = Σ(N_i) / N_T
        - CAIDI = SAIDI / SAIFI  [hours]
        - EENS  = total_ens_kwh  [kWh]
        - LOLP  = (steps with shedding) / total_steps
        - ASAI  = 1 − (interruption_hours / service_hours)
        """
        n_t = self.N_MICROGRIDS
        saidi = self._interruption_mg_hours / n_t if n_t > 0 else 0
        saifi = self._interruption_events / n_t if n_t > 0 else 0
        caidi = saidi / saifi if saifi > 0 else 0
        lolp = (
            self._steps_with_shedding / self._total_steps
            if self._total_steps > 0 else 0
        )
        total_service_hours = self._total_steps * 0.25 * n_t
        asai = (
            1 - self._interruption_mg_hours / total_service_hours
            if total_service_hours > 0 else 1.0
        )

        return StandardReliabilityIndices(
            SAIDI=round(saidi, 4),
            SAIFI=round(saifi, 4),
            CAIDI=round(caidi, 4),
            EENS=round(self.total_ens_kwh, 2),
            LOLP=round(lolp, 6),
            ASAI=round(asai, 6),
        )

    def to_dataframe(self):
        """
        Export per-timestep metrics as a pandas DataFrame.

        Columns: timestamp, total_ens_kwh, gen_energy_kwh, exchanged_kwh,
                 recovery_phase, city_deficit_kw, plus per-MG shed/gen/soc.

        Returns:
            pd.DataFrame if pandas is available, else list of dicts.
        """
        try:
            import pandas as pd
            rows = []
            for d in self.timestep_data:
                row = {
                    'timestamp': d['timestamp'],
                    'total_ens_kwh': d['total_ens_kwh'],
                    'gen_energy_kwh': d['gen_energy_kwh'],
                    'exchanged_kwh': d['exchanged_kwh'],
                    'recovery_phase': d['recovery_phase'],
                    'city_deficit_kw': d.get('city_deficit_kw', 0),
                }
                for mg_id, val in d.get('per_mg_shed', {}).items():
                    row[f'{mg_id}_shed_kw'] = val
                for mg_id, val in d.get('per_mg_gen_kw', {}).items():
                    row[f'{mg_id}_gen_kw'] = val
                for mg_id, val in d.get('per_mg_soc', {}).items():
                    row[f'{mg_id}_soc'] = val
                rows.append(row)
            return pd.DataFrame(rows)
        except ImportError:
            logger.warning("pandas not available; returning raw list of dicts")
            return self.timestep_data

    def finalize(
        self,
        cascade_controller: Optional['CascadeController'] = None,
        stability_monitor: Optional['StabilityMonitor'] = None,
        recovery_controller: Optional['RecoveryController'] = None,
        exchange_bus=None,
        baseline_gen_kwh: float = 0.0,
    ) -> CoordinatedOutageScorecard:
        """Compute final scorecard from accumulated data."""
        recovery_hours = 0.0
        if self.recovery_start and self.recovery_end:
            recovery_hours = (
                self.recovery_end - self.recovery_start
            ).total_seconds() / 3600.0

        gen_reduction = 0.0
        if baseline_gen_kwh > 0:
            gen_reduction = (
                (baseline_gen_kwh - self.gen_energy_kwh)
                / baseline_gen_kwh * 100.0
            )

        std_indices = self.compute_standard_indices()

        return CoordinatedOutageScorecard(
            total_unserved_energy_kwh=round(self.total_ens_kwh, 2),
            critical_unserved_energy_kwh=round(self.critical_ens_kwh, 2),
            recovery_time_hours=round(recovery_hours, 2),
            cascade_events_triggered=(
                cascade_controller.cascade_count if cascade_controller else 0
            ),
            cascade_events_prevented=(
                cascade_controller.cascades_prevented
                if cascade_controller else 0
            ),
            shared_generation_kwh=round(self.shared_energy_kwh, 2),
            demand_reduction_kwh=round(self.demand_reduction_kwh, 2),
            energy_exchanged_kwh=round(self.exchanged_energy_kwh, 2),
            recovery_phases_completed=(
                recovery_controller.phase.value
                if recovery_controller else 0
            ),
            secondary_instability_events=(
                stability_monitor.instability_events
                if stability_monitor else 0
            ),
            mean_recovery_time_hours=round(recovery_hours, 2),
            generator_usage_total_kwh=round(self.gen_energy_kwh, 2),
            generator_usage_reduction_percent=round(gen_reduction, 2),
            standard_indices=std_indices,
        )

    @staticmethod
    def _explain_statistical_tests() -> str:
        """
        Document the statistical validation methodology.

        Returns a description suitable for a paper's methodology section.
        """
        return """
        Statistical Validation Protocol for Monte Carlo Experiments
        ==========================================================

        1. NORMALITY CHECK
           - Shapiro-Wilk test on each metric (H0: data is normally distributed)
           - For n >= 30, Central Limit Theorem applies; parametric tests valid
           - Use scipy.stats.shapiro(data), reject H0 if p < 0.05

        2. PARAMETRIC COMPARISON (if normality holds)
           - Paired t-test between configurations (Config A vs C)
           - H0: mean(metric_A) = mean(metric_C); reject if p < 0.05
           - Report: mean ± 95% CI = mean ± 1.96 * (std / sqrt(n))
           - Effect size: Cohen's d = (mean_A - mean_C) / pooled_std
             - Small: d < 0.2, Medium: 0.2-0.8, Large: d > 0.8

        3. NON-PARAMETRIC BACKUP (if normality fails)
           - Wilcoxon signed-rank test (paired, non-parametric)
           - H0: median difference = 0; reject if p < 0.05
           - Report median and interquartile range (IQR)

        4. MULTIPLE COMPARISON CORRECTION
           - Bonferroni correction: alpha_adj = 0.05 / n_comparisons
           - For 3 configs × 8 metrics = 24 comparisons: alpha = 0.002

        5. CONFIDENCE INTERVALS
           - 95% CI: [mean - 1.96*SE, mean + 1.96*SE]
           - Bootstrap CI (10,000 resamples) as robustness check

        Python implementation:
            from scipy import stats
            t_stat, p_val = stats.ttest_rel(metric_A, metric_C)
            w_stat, p_val = stats.wilcoxon(metric_A, metric_C)
            cohens_d = (np.mean(A) - np.mean(C)) / np.sqrt(
                (np.var(A) + np.var(C)) / 2
            )
        """
